-- Tabela para armazenar anexos dos preparos
CREATE TABLE AGENDA_PREPAROS_ANEXOS (
    ID INTEGER NOT NULL PRIMARY KEY,
    PREPARO_ID INTEGER NOT NULL,
    AGENDA_ID INTEGER NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    NOME_ORIGINAL VARCHAR(255) NOT NULL,
    TIPO_ARQUIVO VARCHAR(100),
    TAMANHO_ARQUIVO INTEGER,
    CAMINHO_ARQUIVO VARCHAR(500) NOT NULL,
    DATA_UPLOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USUARIO_UPLOAD VARCHAR(100),
    CONSTRAINT FK_ANEXOS_AGENDA FOREIGN KEY (AGENDA_ID) REFERENCES AGENDAS(ID)
);

-- Criar sequência para ID auto-incremento
CREATE SEQUENCE SEQ_ANEXOS_PREPAROS;

-- Criar trigger para auto-incremento
CREATE TRIGGER TRG_ANEXOS_PREPAROS_ID
    BEFORE INSERT ON AGENDA_PREPAROS_ANEXOS
    FOR EACH ROW
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(SEQ_ANEXOS_PREPAROS, 1);
    END
END;

-- Criar índices para melhor performance
CREATE INDEX IDX_ANEXOS_AGENDA_ID ON AGENDA_PREPAROS_ANEXOS(AGENDA_ID);
CREATE INDEX IDX_ANEXOS_PREPARO_ID ON AGENDA_PREPAROS_ANEXOS(PREPARO_ID);