-- Estrutura para sistema de confirmação WhatsApp
-- Arquivo: sql_whatsapp_confirmacoes.sql

-- Tabela principal para controle de confirmações
CREATE TABLE WHATSAPP_CONFIRMACOES (
    ID INTEGER NOT NULL,
    AGENDAMENTO_ID INTEGER NOT NULL,
    NUMERO_AGENDAMENTO VARCHAR(50),
    PACIENTE_NOME VARCHAR(200),
    PACIENTE_TELEFONE VARCHAR(20),
    DATA_CONSULTA DATE,
    HORA_CONSULTA TIME,
    MEDICO_NOME VARCHAR(200),
    ESPECIALIDADE_NOME VARCHAR(200),
    UNIDADE_NOME VARCHAR(200),
    
    -- Controle de envio
    STATUS VARCHAR(20) DEFAULT 'pendente', -- 'pendente','enviado','confirmado','cancelado','reagendar','erro'
    DATA_ENVIO TIMESTAMP,
    DATA_RESPOSTA TIMESTAMP,
    TENTATIVAS INTEGER DEFAULT 0,
    
    -- Dados da mensagem
    MENSAGEM_ENVIADA BLOB SUB_TYPE TEXT,
    RESPOSTA_PACIENTE VARCHAR(500),
    WHATSAPP_MESSAGE_ID VARCHAR(100),
    
    -- Metadados
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CREATED_BY VARCHAR(50),
    
    CONSTRAINT PK_WHATSAPP_CONF PRIMARY KEY (ID)
);

-- Gerador de sequência para IDs
CREATE GENERATOR GEN_WHATSAPP_CONFIRMACOES_ID;

-- Trigger para auto-incremento
SET TERM ^^ ;
CREATE TRIGGER TR_WHATSAPP_CONFIRMACOES_BI FOR WHATSAPP_CONFIRMACOES
ACTIVE BEFORE INSERT POSITION 0
AS
BEGIN
    IF (NEW.ID IS NULL) THEN
        NEW.ID = GEN_ID(GEN_WHATSAPP_CONFIRMACOES_ID, 1);
END ^^
SET TERM ; ^^

-- Trigger para atualizar UPDATED_AT
SET TERM ^^ ;
CREATE TRIGGER TR_WHATSAPP_CONFIRMACOES_BU FOR WHATSAPP_CONFIRMACOES
ACTIVE BEFORE UPDATE POSITION 0
AS
BEGIN
    NEW.UPDATED_AT = CURRENT_TIMESTAMP;
END ^^
SET TERM ; ^^

-- Índices para performance
CREATE INDEX IDX_WHATSAPP_CONF_AGENDAMENTO ON WHATSAPP_CONFIRMACOES (AGENDAMENTO_ID);
CREATE INDEX IDX_WHATSAPP_CONF_STATUS ON WHATSAPP_CONFIRMACOES (STATUS);
CREATE INDEX IDX_WHATSAPP_CONF_DATA_CONSULTA ON WHATSAPP_CONFIRMACOES (DATA_CONSULTA);
CREATE INDEX IDX_WHATSAPP_CONF_TELEFONE ON WHATSAPP_CONFIRMACOES (PACIENTE_TELEFONE);

-- Comentários nas colunas
COMMENT ON COLUMN WHATSAPP_CONFIRMACOES.STATUS IS 'Status: pendente, enviado, confirmado, cancelado, reagendar, erro';
COMMENT ON COLUMN WHATSAPP_CONFIRMACOES.TENTATIVAS IS 'Número de tentativas de envio';
COMMENT ON COLUMN WHATSAPP_CONFIRMACOES.WHATSAPP_MESSAGE_ID IS 'ID da mensagem no WhatsApp para tracking';

-- Inserir dados iniciais se necessário
-- INSERT INTO WHATSAPP_CONFIRMACOES (AGENDAMENTO_ID, STATUS) VALUES (0, 'teste');